spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    discovery:
      enabled: true
  application:
    name: gateway
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost
server:
  port: 8087
